### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by naveennirban** [PushpenderIndia/ragno#1]
Traceback (most recent call last):
  File "ragno.py", line 164, in <module>
    final_url_list = crawl.start()
  File "ragno.py", line 44, in start
    self.getCommonCrawlURLs(self.domain, self.want_subdomain, ["http://index.commoncrawl.org/CC-MAIN-2018-22-index"])
  File "ragno.py", line 149, in getCommonCrawlURLs
    url = f"{api}?url={wild_card+domain}/*&fl=url"     
TypeError: can only concatenate str (not "NoneType") to str

**Comment by naveennirban** [comment]
Add help code on file run so that if we run the direct file, the user get file documentation instead of error.
